"""update follow

Revision ID: 36037b8c5291
Revises: 0be81cab2567
Create Date: 2025-03-17 21:19:45.338903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36037b8c5291'
down_revision = '0be81cab2567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('follower_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('followed_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.alter_column('followed_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('follower_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
