"""update user to replier in replies

Revision ID: 371f54b90710
Revises: 6a90949a9c69
Create Date: 2025-03-13 23:06:14.896405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371f54b90710'
down_revision = '6a90949a9c69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replier_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_replies_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_replies_replier_id_users'), 'users', ['replier_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_replies_replier_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_replies_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('replier_id')

    # ### end Alembic commands ###
