"""add relationship for likes

Revision ID: 5a33f91c7b4b
Revises: ac65ca75547e
Create Date: 2025-03-10 13:40:34.942853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a33f91c7b4b'
down_revision = 'ac65ca75547e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_liker_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('liked_comment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_likes_liked_comment_id_comments'), 'comments', ['liked_comment_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_likes_comment_liker_id_users'), 'users', ['comment_liker_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_likes_comment_liker_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_likes_liked_comment_id_comments'), type_='foreignkey')
        batch_op.drop_column('liked_comment_id')
        batch_op.drop_column('comment_liker_id')

    # ### end Alembic commands ###
